sources:
  - name: AsociacionCivil
    url: "https://www.youtube.com/c/CanalesAsociaci%C3%B3nCivil/videos"
    subs: true
    auto_subs: false
    generate_subs: true

  - name: Videolibros(public)
    url: "https://www.youtube.com/@VideolibrosLSA/videos"
    subs: true
    auto_subs: false
    generate_subs: true

  - name: Videolibros(private)
    path: "scraped/videolibros_private.txt"
    subs: true
    auto_subs: false
    generate_subs: true

  - name: CNSordos
    url: "https://www.youtube.com/@CNSORDOSARGENTINA/videos"
    subs: true
    auto_subs: false
    generate_subs: false

  - name: Locufre
    url: "https://www.youtube.com/channel/UCPJr7e9V_07DAID60F0pXVw"
    subs: true
    auto_subs: true
    generate_subs: false

options:
  download:
    format: "(bestvideo[vcodec^=avc][height<=1080]/bestvideo[vcodec^=avc])  +bestaudio[ext=m4a]/best"
    sub_langs:
      - "es.*"
  video_audio_separation:
    delete_original: false
  whisper:
    model: "large-v3-turbo"
    device: "cuda"
    language: "es"