sources:
  - name: AsociacionCivil
    url: "https://www.youtube.com/c/CanalesAsociaci%C3%B3nCivil/videos"
    subs: true
    auto_subs: false
    generate_subs: true

  - name: Videolibros(public)
    url: "https://www.youtube.com/@VideolibrosLSA/videos"
    subs: true
    auto_subs: false
    generate_subs: true

  - name: Videolibros(private)
    path: "scraped/videolibros_private.txt"
    subs: true
    auto_subs: false
    generate_subs: true

  - name: CNSordos
    url: "https://www.youtube.com/@CNSORDOSARGENTINA/videos"
    subs: true
    auto_subs: false
    generate_subs: false

  - name: Locufre
    url: "https://www.youtube.com/channel/UCPJr7e9V_07DAID60F0pXVw"
    subs: true
    auto_subs: true
    generate_subs: false

options:
  download:
    format: "(bestvideo[vcodec^=avc][height<=1080]/bestvideo[vcodec^=avc])  +bestaudio[ext=m4a]/best"
    sub_langs:
      - "es.*"
    cookies_from_browser: "firefox"
  video_audio_separation:
    delete_original: false
  whisper:
    model: "large-v3-turbo"
    device: "cuda"
    language: "es"
  bounding_boxes:
    model_path: "models/yolo11m.pt"
    fps: 6
  landmarks:
    num_workers: 1
    fps: 6
    max_clip_frame_separation: 1
    min_clip_duration_frames: 36  # fps * 6 seconds
    moving_threshold: 0.25
    write_buffer_size: 160
    mode: "balanced"        # rtmlib mode: balanced, performance, lightweight
    backend: "onnxruntime"  # onnxruntime, opencv, openvino, tensorrt
    device: "cuda"